import "./globals.css";
import ProviderWrapper from "@/app/_providers/ProviderWrapper";
import SessionProviderWrapper from "@/app/_providers/SessionProviderWrapper";
import ThemeRegistry from "@/lib/theme/ThemeRegistry";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AppHeader from "@/components/shared/appHeader";
import Footer from "@/components/shared/footer";

export const metadata = {
  title: "Food ordering app",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <ThemeRegistry>
          <SessionProviderWrapper>
            <ProviderWrapper>
              <AppHeader />
              <main>{children}</main>
              <Footer />
            </ProviderWrapper>
          </SessionProviderWrapper>
        </ThemeRegistry>
        <ToastContainer rtl position="top-center" />
      </body>
    </html>
  );
}
