import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/footer";
import ProviderWrapper from "@/components/redux/ProviderWrapper";
import SessionProviderWrapper from "@/components/common/SessionProviderWrapper";
import ThemeRegistry from "@/components/common/ThemeRegistry";
import AppHeader from "@/components/common/appHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: import("react").ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>
          <SessionProviderWrapper>
            <ProviderWrapper>
              <AppHeader />
              <main>{children}</main>
              <Footer />
            </ProviderWrapper>
          </SessionProviderWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
