import "./globals.css";
import Footer from "@/components/common/footer";
import ProviderWrapper from "@/components/providers/ProviderWrapper";
import SessionProviderWrapper from "@/components/providers/SessionProviderWrapper";
import ThemeRegistry from "@/components/common/ThemeRegistry";
import AppHeader from "@/components/common/appHeader";
import { ReactNode } from "react";
import QueryProvider from "@/components/providers/QueryProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; 

export const metadata = {
  title: "Food ordering app",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <ThemeRegistry>
          <SessionProviderWrapper>
            <ProviderWrapper>
              <QueryProvider>
                <AppHeader />
                <main>{children}</main>
                <Footer />
              </QueryProvider>
            </ProviderWrapper>
          </SessionProviderWrapper>
        </ThemeRegistry>
        <ToastContainer rtl position="top-center" />
      </body>
    </html>
  );
}
